actionscript: ActionScript
applescript: AppleScript
awk: Awk
c: C
charp: C#
cpp: C++
clojure: Clojure
coffeescript: CoffeeScript
cl: Common Lisp
d: D
dart: Dart
delphi: Delphi
erlang: Erlang
go: Go
groovy: Groovy
haskell: Haskell
java: Java
javascript: JavaScript
json: JSON
lua: Lua
objc: Objective-C
ocaml: OCaml
perl: Perl
php: PHP
python: Python
ruby: Ruby
rust: Rust
scala: Scala
smalltalk: Smalltalk
vim: VimL
xml: XML
xslt: XSLT
